## Colors configuration
[colors.primary]
background = "#070707"
foreground = "#ed8182"

[colors.normal]
black   = "#070707"
red     = "#423F3F"
green   = "#524F50"
yellow  = "#8F0C0D"
blue    = "#AE0B0B"
magenta = "#AE2121"
cyan    = "#CE0F0F"
white   = "#ed8182"

[colors.bright]
black   = "#a55a5b"
red     = "#423F3F"
green   = "#524F50"
yellow  = "#8F0C0D"
blue    = "#AE0B0B"
magenta = "#AE2121"
cyan    = "#CE0F0F"
white   = "#ed8182"
